name: PR Branch Check

# Add repository-level permissions
permissions:
  pull-requests: write
  issues: write
  contents: write
  statuses: write

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - master

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check and Comment on PR
        if: |
          (github.event.pull_request.head.repo.fork == true && 
          (github.event.pull_request.head.ref == 'main' || github.event.pull_request.head.ref == 'master')) ||
          (github.event.pull_request.base.ref == 'main' || github.event.pull_request.base.ref == 'master')
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let message = '';
            if (context.payload.pull_request.head.repo.fork && 
                (context.payload.pull_request.head.ref === 'main' || context.payload.pull_request.head.ref === 'master')) {
              message += '⚠️ This PR cannot be merged because it comes from a fork\'s main/master branch. Please create a feature branch and submit your PR from there.\n\n';
            }
            if (context.payload.pull_request.base.ref === 'main' || context.payload.pull_request.base.ref === 'master') {
              message += '⚠️ PRs cannot target main/master branch directly. Please target a development or feature branch instead.';
            }
            
            // Post the comment
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: message
            });
            
            // Close the PR
            await github.rest.pulls.update({
              ...context.repo,
              pull_number: context.issue.number,
              state: 'closed'
            });
